# Generated by Django 4.2.22 on 2025-06-10 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daamduu_yemek_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
    ]
