# Generated by Django 4.2.22 on 2025-06-10 22:27

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('daamduu_yemek_app', '0002_remove_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('calories', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('image', models.ImageField(upload_to='dishes/')),
            ],
        ),
        migrations.CreateModel(
            name='DailyMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('dish1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_dish1', to='daamduu_yemek_app.dish')),
                ('dish2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_dish2', to='daamduu_yemek_app.dish')),
                ('dish3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_dish3', to='daamduu_yemek_app.dish')),
                ('dish4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_dish4', to='daamduu_yemek_app.dish')),
            ],
        ),
    ]
