# Generated by Django 4.2.22 on 2025-06-10 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daamduu_yemek_app', '0003_dish_dailymenu'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('used', 'Used')], default='active', max_length=10),
        ),
    ]
